version: '2'
services:
  selenium:
    container_name: "selenium"
    build: ./selenium
    environment:
      - SCREEN_WIDTH=1366
      - SCREEN_HEIGHT=768
      - SCREEN_DEPTH=24
      - SCREEN_DPI=96
    expose:
      - '4444'
      - '5900'
      - '2011'
    ports:
      - "4444:4444"
      - "5900:5900"
      - "2011:2011"
    volumes:
      - ./logs:/home/seluser/.pm2/logs/
      - /dev/shm:/dev/shm
    restart: always
    tty: true
